# File: azure-template-publish-job.yml
# Date: 8-Jul-2019 jdw split out from original pipeline
#
##
parameters:
  tox: ""
  python: ""
  os: "linux"
  fixtures: ""

jobs:
- job: ${{ format('publish_{0}_{1}', parameters.tox, parameters.os) }}
  pool:
    ${{ if eq(parameters.os, 'macos') }}:
      vmImage: 'macOS-10.14'
    ${{ if eq(parameters.os, 'linux') }}:
      vmImage: 'ubuntu-latest'
  dependsOn:
  - ${{ format('build_test_{0}_{1}', parameters.tox, parameters.os) }}
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  #
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: ${{ parameters.python }}
        addToPath: true
      displayName: setup python
    #
    #- checkout: self
    #  submodules: true
    #
    - download: current
      artifact: ${{ format('sw_{0}_{1}', parameters.tox,  parameters.os) }}
    #
    - script: ls -lR $(Pipeline.Workspace)/${{ format('sw_{0}_{1}', parameters.tox, parameters.os) }}
      displayName: "Listing of downloaded artifacts"
    #
    - script: python -m pip install --upgrade pip twine setuptools wheel
      displayName: 'Install packaging tools'
    #
    - task: DownloadSecureFile@1
      name: pypicred
      displayName: 'Download PyPI credentials'
      inputs:
        secureFile: 'PYPIRC-AZURE'

    - script: twine upload --verbose --skip-existing -r pypi  --config-file $(pypicred.secureFilePath) $(Pipeline.Workspace)/${{ format('sw_{0}_{1}', parameters.tox, parameters.os) }}/*
      displayName: "Upload sdist and wheel to PyPi ..."
      continueOnError: true
    #
